Config = {R}

Config.Activationkey = 167
Config.ActivationCommand = "vehiclemenu"

Config.DiscordMemberAcePerm = "VehicleSpawner.member"
Config.WhitelistedAcePerm = "VehicleSpawner.leo"
Config.ServerBoosterAcePerm = "VehicleSpawner.server_booster"
Config.Tier1AcePerm = "VehicleSpawner.tier1"
Config.Tier2AcePerm = "VehicleSpawner.tier2"
Config.Tier3AcePerm = "VehicleSpawner.tier3"


Config.DiscordMemberVehicles = {
    {"Acura NSX 2F2F","acura2f2f"  },
    {"Acura  NSX","filthynsx"  },
    {"Afla Romeo  Giulietta","argiu"  },
    {"Alfa Romeo 105GT","105gt"  },
    {"Alfa Romeo 155 Q4","155q4"  },
    {"Alfa Romeo GTV 6","gtv6"  },
    {"Alfa Romeo Giulia","giulia"  },
    {"Alfa Romeo  TZ3","tz3"  },
    {"Alfa Romeo  4C","4c"  },
    {"AMC Javelin AMX 401","jav401"  },
    {"Ariel Nomad","nomad"  },
    {"Aston Martin Zagato V12","zagatov12"  },
    {"Aston Martin DBX","dbx"  },
    {"Aston Martin Vantage V600","v600"  },
    {"Aston Martin Vantage","vantage"  },
    {"Aston Martin  Cygnet","cygnet"  },
    {"Audi TT Gen 1","yAudiTTmk1"  },
    {"Audi Q7 S","sq72016"  },
    {"Audi  Quattro","audquattros"  },
    {"Audi  S3 2015","2015s3"  },
    {"Audi  A3","s3sedan"  },
    {"Audi  RS7","rs7"  },
    {"BMW E28 M5","m5e28"  },
    {"BMW 325 ET","325et"  },
    {"BMW 507","bmw507"  },
    {"BMW E34","bmwe34"  },
    {"BMW S 1000 RR","bmws"  },
    {"BMW E21","e21"  },
    {"BMW 318i","e30c"  },
    {"BMW M6","oldm6"  },
    {"BMW E53 X5","x5e53"  },
    {"BMW  635","635"  },
    {"BMW  E30 M3","m3e30"  },
    {"Brabus 700G","brabus700"  },
    {"Buick Grand National X","bgnx"  },
    {"Buick  Century","cnty"  },
    {"Buick  GSX","gsxb"  },
    {"Cadillac Escalade '21","cesc21"  },
    {"Cadillac  Eldorado 78","e78"  },
    {"Cadillac  ATS V","cats"  },
    {"Chevrolet Impala '96","impala"  },
    {"Chevrolet Impala SS","impalass"  },
    {"Chevrolet Z28 1979","z2879"  },
    {"Chevrolet  Nova","nova"  },
    {"Chrysler New Yorker 1975","newyorker75"  },
    {"Chrysler  300 SRT8","300srt8"  },
    {"Daewoo Leganza","leganza"  },
    {"Dodge Charger R/T 1970","rt70"  },
    {"Dodge  Charger","16charger"  },
    {"Dodge  Viper '99","99viper"  },
    {"Ferrari  575M","575m"  },
    {"Fiat  Fiorino","fiorino"  },
    {"Fiat  Punto","punto"  },
    {"Ford Focus","focusrs"  },
    {"Ford F-150 Ranger XLT '78","f15078"  },
    {"Ford Cortina","cortina"  },
    {"Honda Civic TypeR","fk2"  },
    {"Honda Odyssey","ody18"  },
    {"Honda NSX NA1","na1"  },
    {"Honda  S2000","ap2"  },
    {"Honda  Civic SI VTEC","civic"  },
    {"Honda  Civic Type R EK9","ek9"  },
    {"Honda  S2000","2f2fs2000"  },
    {"Hyundai Sonata","sont18"  },
    {"Hyundai Velaster","veln"  },
    {"Hyundai  Coupe Tiburon","tiburon"  },
    {"Hyundai  Kona","hkona"  },
    {"Infiniti  Q30","q30"  },
    {"Jaguar XFR","xfr"  },
    {"Jaguar  XJS","jagxjs80"  },
    {"Jeep SRT","srt8"  },
    {"Jeep SRT","srt8b"  },
    {"Kia  Forte Koup","koup"  },
    {"Lancia Delta Integrale","deltaintegrale"  },
    {"Lancia Delta","lanciad"  },
    {"Lexus gx460 ","gx460"  },
    {"Lexus IS350","is350mod"  },
    {"Lexus CT 200H","CT200H"  },
    {"Lotus Carlton","carlton"  },
    {"Maserati GranTurismo '10","mgrantur2010"  },
    {"Maserati  Ghibli","ghis2"  },
    {"Maserati  Levante","levante"  },
    {"Mazda RX-3","rx3"  },
    {"Mazda FC RX-7","fc3s"  },
    {"Mazda FD RX-7","fd"  },
    {"Mazda  RX-7","rx7tunable"  },
    {"Mercedes Brabus B63S","b63s"  },
    {"Mercedes Maybach S650","19S650"  },
    {"Mercedes AMG C63 S","c63w205"  },
    {"Mercedes AMG GL 63","gl63"  },
    {"Mercedes Maybach Emperor","scaldarsi"  },
    {"Mercedes AMG GT","amggt"  },
    {"Mercedes AMG CLA 45","cla45sb"  },
    {"Mercedes AMG S63","mers63c"  },
    {"Mitsubishi 3000 GT","3000gt"  },
    {"Nissan Armada Platinum","tule"  },
    {"Nissan 300zx","z32"  },
    {"Nissan Qashqai","qashqai16"  },
    {"Opel R3","2dopelr3"  },
    {"Opel Astra J","astraj"  },
    {"Peugeot  204","peugeot204"  },
    {"Porsche  Cayenne Turbo","cayenneturbo"  },
    {"Porsche  Macan Turbo","macan"  },
    {"Renault 4 GTL","renault4"  },
    {"Renault Twingo","twingo"  },
    {"Renault 5TB","yRenault5TB"  },
    {"Renault 5TA","yRenault5TA"  },
    {"Renault  16","renault16"  },
    {"Subaru  Impreza STI 228","sim22"  },
    {"Subaru  Impreza WRX '10","ff4wrx"  },
    {"Tesla Model X","teslax"  },
    {"Toyota Celica","celica"  },
    {"Toyota Camry XV50","camv50"  },
    {"Toyota Camry V55","camry55"  },
    {"Toyota Camry","camry18"  },
    {"Toyota AE86 Tureno","ae86"  },
    {"Toyota Supra Turbo","a80"  },
    {"Volkswagen Golf GTI","golfgti"  },
    {"Volkswagen Golf MK7 R","golf7r"  },
    {"Volkswagen  Toureg R50","R50"  },
    {"Volkswagen  Rabbit GTI","mk1rabbit"  },
    {"Volkswagen  Amarok","amarok"  },
    {"Volvo 850 R","volvo850r"  },
    {"Volvo S60","s60pole"  },
    {"Volvo V242","v242"  }
      
    
}

Config.WhitelistedVehicles = {
    {"Aston Martin Vanquish","ast"},
    {"Audi RS4","rs4avant"  },
    {"Dodge Challenger","16challenger"  },
    {"Dodge  Charger '69","69charger"  },
    {"Ford Mustang '72","boss429"  },
    {"GMC Yukon Denali","gmcyd"  },
    {"Honda Civic TypeR","fk8"  },
    {"Jaguar XJ","xj"  },
    {"Jaguar  F-Type Project 7","p7"  },
    {"Mercedes C63 LibertyWalk","63lb"  },
    {"Mercedes AMG GTR","amggtr"  },
    {"Mercedes  V250 Bluetec","v250"  },
    {"Mercedes  504 Coupe","504coupe"  },
    {"Mitsubishi Eclipse","eclipse"  },
    {"Mitsubishi  Evo X FQ-400","lanex400"  },
    {"Mitsubishi  Eclipse","fnfmits"  },
    {"Nissan 370z","370z"  },
    {"Nissan Skyline GTR 1993","majsr"  },
    {"Nissan Titan","nissantitan17"  },
    {"Porsche  928 GTS","p928"  },
    {"Porsche  718 Cayman GT4","porschehw"  },
    {"Range Rover Sport 2008","rrs08"  },
    {"Subaru 03' WRX STI","subwrx"  },
    {"Subaru 01' WRX STI","SubaruSTI7"  },
    {"Subaru  13' WTX STI","sti"  },
    {"Ford  F-350 Super Duty","superduty"  }
      
}

Config.ServerBoosterVehicles = {
    {"Alfa Romeo 155","155alfa"  },
    {"Audi RS3 2018","rs318"  },
    {"Audi  ABT","rs5r"  },
    {"Audi  S5","auds5"  },
    {"Audi  RS3","rs3"  },
    {"Dodge Ram 2500","ram2500"  },
    {"Dodge Viper 2013","viper"  },
    {"Ferrari 412","412"  },
    {"Fiat Abarth 595 Esseesse","yFiat595ssA"  },
    {"Fiat  124 Spider","124spider"  },
    {"Ford Mustang Boss 302","boss302"  },
    {"Ford F-150 Raptor","f150"  },
    {"Honda NSX NC1","nc1"  },
    {"Honda Civic EJ1","hcej1"  },
    {"Hyundai Equus","equus15"  },
    {"Hyundai  Genesis","gencoupe"  },
    {"Infiniti  Q60 Project Black S","inf"  },
    {"Jaguar F-Pace","fpacehm"  },
    {"Jeep Wrangler '12","jeep2012"  },
    {"Jeep Track Hawk","trhawk"  },
    {"Kia Stinger GT","kiagt"  },
    {"Lamborghini Urus","urus"  },
    {"Lancia Rally 37","l37"  },
    {"Lotus 111 S","l111s"  },
    {"Lotus  Esprit V8","esprit02"  },
    {"Lumma  L50 LI","lumma750"  },
    {"Maserati Levante (Mansory)","mlmansory"  },
    {"Maserati  Novitec","mlnovitec"  },
    {"Mazda RX7 DT","fnfrx7dom"  },
    {"Mazda RX  450H","rx450h"  },
    {"Mazda  MX5 (Stanced)","mx5326"  },
    {"Mercedes AMG E63","e63amg"  },
    {"Mercedes E400","e400"  },
    {"Mercedes AMG G65","g65amg"  },
    {"Mitsubishi Lancer Evo 7","2f2fmle7"  },
    {"Mitsubishi 3000 GT (Stanced)","3000gta"  },
    {"Mitsubishi Lancer EVO CP9A","cp9a"  },
    {"Mitsubishi  Evo X FQ 400","evo10"  },
    {"Nissan Skyline GTR","skyline"  },
    {"Nissan Skyline C110","skylinec110"  },
    {"Porsche 1600 (Open Top)","356ac"  },
    {"Porsche 968","968"  },
    {"Porsche Turbo33","turbo33"  },
    {"Range Rover Sport 2012","rr12"  },
    {"Range Rover Sport 2018 (STARTECH)","rrst"  },
    {"Renault Clio Sport V6","cliov6"  },
    {"Subaru WRX STI","gdwrxsti"  },
    {"Tesla Model S Plaid","teslapd"  },
    {"Volkswagen  Jetta","fnfjetta"  }

}

Config.Tier1Vehicles = {
    {"Acura NSX Gen 1","acuransx"  },
    {"Aston Martin Vantage GT12","vgt12"  },
    {"Audi TTS '07","tts07"  },
    {"Audi Q7","q7"  },
    {"Audi  S5 LB","lwas5"  },
    {"Bentley Bentayga","bbentayga"  },
    {"BMW 440i","440i"  },
    {"BMW E53 X5","x5e53"  },
    {"BMW X6 M","x6m"  },
    {"BMW E60 M5","m5e60"  },
    {"BMW  Z3 Hatchback","z3"  },
    {"BMW  E46 M3","m3e46"  },
    {"BMW  E34 M5","e34"  },
    {"BMW  760I","bmwe65"  },
    {"Chevelle SS 1970","chevelle1970"  },
    {"Chevrolet  C10 Custom","c10custom"  },
    {"Chrysler ME-412","me412"  },
    {"Dodge Charger R/T F8 '68","chargerf8"  },
    {"Dodge  Viper ACR","acr"  },
    {"Ferrari 512BB","bb512"  },
    {"Ferrari Dino 246 GT","dino"  },
    {"Ferrari 288 GTO","f288gto"  },
    {"Ferrari  488 (2)","4881"  },
    {"Ferrari  612ss","612ss"  },
    {"Ferrari  612","fer612"  },
    {"Ford Capri Mk3 Race Car","fordcapri"  },
    {"Ford Mustang GT","mgt"  },
    {"Ford Mustang Shelby GT500","mst"  },
    {"GMC Denali Sierra","denalihd"  },
    {"Honda Civic Type R","hondacivictr"  },
    {"Honda  NXS RB","nsexrb"  },
    {"Jaguar F-Type","ftype"  },
    {"Jaguar XE S","xes2015"  },
    {"Jaguar  XE SV Project 8","jagpr8"  },
    {"Jeep US Army","trailcat"  },
    {"Land Rover DEF '90","def90"  },
    {"Lotus  Exige","exigev6"  },
    {"Maserati GT4","mcgt4"  },
    {"Mazda RX7","2f2frx7"  },
    {"Mazda RX7 Veilside","fnfrx7"  },
    {"Mazda  MX-5 Miata","na6"  },
    {"Mercedes 300SL Gullwing","mb300sl"  },
    {"Mercedes  SLS AMG","slsamg"  },
    {"Mitsubishi Lancer Evo MR","evo9mr"  },
    {"Mitsubishi  Lancer Evo 2009","evo9"  },
    {"Mitsubishi  Triton L200","l200"  },
    {"Nissan 350Z (Body Kit)","350zdk"  },
    {"Nissan 350Z (Body Kit 2)","350zm"  },
    {"Nissan Silvia S15","silvias15"  },
    {"Nissan GTR","gtr"  },
    {"Peugeot 205 turbo ","yPG205t16A"  },
    {"Peugeot 205 turbo","yPG205t16B"  },
    {"Porsche 718 RS '60","718rs"  },
    {"Porsche 911 Carrera S","992c"  },
    {"Porsche  Panamera Turbo","panamera17turbo"  },
    {"Porsche  911 Widebody","pruf"  },
    {"Range Rover SVR","svr16"  },
    {"Rolls Royce Wraith","wraith"  },
    {"Rolls Royce  Phantom","rrphantom"  },
    {"Toyota  GT86 LB","gt86lb"  }

}

Config.Tier2Vehicles = {
    {"Alfa Romeo  Tipo 33 Stradale","alfa67"  },
    {"Ariel Atom","atom"  },
    {"Aston Martin  DB11 Mansory Cyrus","cyrus"  },
    {"Audi R8","r820"  },
    {"Audi Q8","q820"  },
    {"Bentley  Continental GT '13","contgt13"  },
    {"Bentley  Continental GT '11","contgt2011"  },
    {"BMW C2 (CONCEPT)","bmc2"  },
    {"BMW M1","m1"  },
    {"BMW F82 M4","m4f82"  },
    {"BMW M8 GTE","m8gte"  },
    {"BMW I8","i8"  },
    {"BMW M5","e60"  },
    {"BMW  M1 Procar","m1procar"  },
    {"Bugatti  Centodieci","bugatticentodieci"  },
    {"Chevrolet Super Snake '16","ccss16"  },
    {"Chevrolet  Camaro ZL1 '17","zl12017"  },
    {"Corvette C7","c7"  },
    {"Corvette ZR1","corvetteZR1"  },
    {"Ferarri  F12","f12m"  },
    {"Ferrari F60","f60"  },
    {"Ferrari  488","488"  },
    {"Ferrari  GTO","gto"  },
    {"Gemballa MIG-U1","mig"  },
    {"Jaguar XJ220","xj220"  },
    {"Koenigsegg Agera RS","agerars"  },
    {"Koenigsegg CCX","ccx"  },
    {"Lamborghini Diablo GTR","500gtrlam"  },
    {"Lamborghini Sesto","sesto"  },
    {"Lamborghini  Huracan GT3","lhgt3"  },
    {"Lamborghini  Huracán Performante","18performante"  },
    {"Lamborghini  Asterion","asterion"  },
    {"Lamborghini  Countach 5000 QV","count6"  },
    {"Lamborghini  Gallardo Superleggera","gallardosuperlb"  },
    {"Lamborghini  Aventador LP 700","lp700"  },
    {"Lotus  Evora","evora"  },
    {"Maserati MC12","mc12"  },
    {"Mazda Tokyo Drift RX-7","rx7veilside"  },
    {"McLaren 720S","720s"  },
    {"McLaren MP4-412C","mp412c"  },
    {"McLaren P1","p1"  },
    {"McLaren 600 LT","600LT"  },
    {"McLaren 675 LT","675lt"  },
    {"Mitsubishi Lancer Evo 8 F&F","fnflan"  },
    {"Nissan Skyline GTR","fnf4r34"  },
    {"Nissan GT-R Nismo","nismo20"  },
    {"Noble  M600","m600"  },
    {"Porsche 718","718"  },
    {"Porsche 718 Boxster","718boxster"  },
    {"Porsche 911 Turbo S","911turbos"  },
    {"Porsche  993 RWB","993rwb"  },
    {"Renault Megane Trophy","renaultm"  },
    {"Renault  Sport RS","sportrs"  },
    {"Renault  R.S 19","f1"  },
    {"Saleen S7","ss7"  }
      
}

Config.Tier3Vehicles = {
        
    {"Aston Martin Valkyrie","avalk"  },
    {"Aston Martin Vulcan AMR","vulcanamr"  },
    {"Audi  R8 LMS GT3","audir8lms2"  },
    {"BAC Mono","bac2"  },
    {"BMW F90 M5","m5f90"  },
    {"BMW  F13 M6","m6f13"  },
    {"BMW  M5","bmci"  },
    {"Bugatti Chiron '17","2017chiron"  },
    {"Bugatti Chiron '19","2019chiron"  },
    {"Bugatti  Royale","royale"  },
    {"Bugatti  EB 110","eb110"  },
    {"Ferrari 488 GTB","488gtb"  },
    {"Ferrari 488 Pista","pista"  },
    {"Ferrari Pista","pistas"  },
    {"Ferrari F355 Berlinetta","f355"  },
    {"Ferrari F40","f40"  },
    {"Ferrari  430 S","f430s"  },
    {"Ferrari  458","f458"  },
    {"Ferrari  F80","f80"  },
    {"Ferrari  Monza","monza"  },
    {"Ferrari  812","f812"  },
    {"Ferrari  488 GT3 Evo","fgt3"  },
    {"Ferrari  FXX-K","fxxk"  },
    {"Ferrari  GT 350","fastback"  },
    {"Ferrari  California T","fct"  },
    {"Ford GT Le Mans","gtrlms"  },
    {"Ford GT '17","gt17"  },
    {"Gumpert Apollo","apollos"  },
    {"Koenigsegg  Jesko","jes"  },
    {"Koenigsegg  Agera R","KoenigseggAgeraR"  },
    {"Lamborghini 610 LP","610lb"  },
    {"Lamborghini  Aventador J","avj"  },
    {"Lamborghini Terzo","terzo"  },
    {"Lamborghini  Diablo SV","diablo"  },
    {"Lamborghini  Huracan (Custom/Stanced)","huralbcamber"  },
    {"Lamborghini  Huracan (Custom)","huralbnormal"  },
    {"Lamborghini  Huracan LP 610","lp610"  },
    {"Lamborghini  Murcielago LP 670","lp670sv"  },
    {"Lamborghini  Centenario LP770","lp770"  },
    {"Lamborghini  Gallardo P570","lp570"  },
    {"Mercedes  Sauber C9","clklm"  },
    {"Nissan Vision Gran Turismo","gtr2020"  },
    {"Pagani Huayra BC","bc"  },
    {"Pagani Zonda Cinque","zondac"  },
    {"Pagani Zonda R","zondar"  },
    {"Pagani  Huayra","huayra"  },
    {"Porsche 918 Spyder","918"  },
    {"Porsche 911 Turbo","911tbs"  },
    {"Praga R1","pragar1"  },
    {"Radical RXC","radical"  }

    
}